<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <artifactId>showcase</artifactId>
    <version>1.0.2</version>
    <name>MarketShowCase</name>

    <parent>
        <groupId>com.maono</groupId>
        <artifactId>MarketApplication</artifactId>
        <version>1.0.2</version>
    </parent>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>com.redis.testcontainers</groupId>
            <artifactId>testcontainers-redis</artifactId>
            <version>1.6.4</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-csv</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>mockwebserver</artifactId>
            <version>5.3.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.12.0</version>
                <executions>
                    <execution>
                        <id>generate-paymentservice-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/../paymentservice/src/main/resources/openapi-spec.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>webclient</library>
                            <output>${project.build.directory}/generated-sources/openapi/paymentservice-client</output>
                            <apiPackage>com.maono.marketapplication.paymentservice.client.api</apiPackage>
                            <modelPackage>com.maono.marketapplication.paymentservice.client.model</modelPackage>
                            <invokerPackage>com.maono.marketapplication.paymentservice.client.invoker</invokerPackage>
                            <addTestCompileSourceRoot>false</addTestCompileSourceRoot>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <generateAuthentication>false</generateAuthentication>
                                <useJakartaEe>true</useJakartaEe>
                                <serializationLibrary>jackson</serializationLibrary>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>
